variables:
  targetPath:  '$(Build.SourcesDirectory)/H5/H5.Build.Target/H5.Build.Target.csproj'
  buildConfiguration: 'Release'
  targetVersion: yy.M.$(build.buildId)

pool:
  vmImage: 'windows-latest'

trigger: 
  branches:
    include:
    - master
  paths:
    include:
    - H5/H5.Build.Target/*
    - .devops/build-h5-target.yml

pr: none

steps:
- checkout: self
  
- script: |
    echo "Commit message: $(Build.SourceVersionMessage)"

- task: UseDotNet@2
  displayName: 'Use .NET 9.0 SDK'
  inputs:
    packageType: sdk
    version: 9.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: PowerShell@2
  displayName: 'Create CalVer Version'
  inputs:
    targetType: 'inline'
    script: |
      $dottedDate = (Get-Date).ToString("yy.M")
      $buildID = $($env:BUILD_BUILDID) 
      $newTargetVersion = "$dottedDate.$buildID"
      Write-Host "##vso[task.setvariable variable=targetVersion;]$newTargetVersion"
      Write-Host "Updated targetVersion to '$newTargetVersion'"

- task: DotNetCoreCLI@2
  displayName: 'restore nuget'
  inputs:
    command: 'restore'
    projects: '$(targetPath)'

- task: DotNetCoreCLI@2
  displayName: 'pack nuget'
  inputs:
    command: 'pack'
    packagesToPack: '$(targetPath)'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'
    buildProperties: 'Version="$(targetVersion)"'

- task: NuGetCommand@2
  displayName: 'push nuget'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/h5.Target.$(targetVersion).nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity-org'